[docs] removes prototype examples and uses classes instead
broccolijs/broccoli-persistent-filter pull request #209
Opened 2020-11-10 01:12 UTC by gabrielcsapo

# Motivation

Moving the examples to show the class based approach will help keep the docs uniform in what we are suggesting people do.

2020-11-10 08:14 UTC, lifeart approved these changes

2021-01-11 19:07 UTC, gabrielcsapo commented
@stefanpenner would you be able to review?

2021-01-13 17:33 UTC, rwjblue requested changes

2021-01-13 17:33 UTC, rwjblue commented on README.md
> +
```suggestion
```

2021-01-13 17:33 UTC, rwjblue commented on README.md
> +
I think we don't need this constructor for the purposes of the example (which is only about `cacheKey`)

```suggestion
```

2021-01-13 17:34 UTC, rwjblue approved these changes

2021-01-13 17:34 UTC, merged